### ISSUE TITLE
Architectural Design

### ISSUE THREAD

**Issue by amolsangar** [airavata-courses/Puzzles#1]
Issue for architectural design discussion

**Comment by amolsangar** [comment]
![Initial Arch Diagram](https://user-images.githubusercontent.com/41895348/151746229-ad95369c-660b-4d30-b0a6-208f06c88b05.jpg)

Initial Diagram

**Comment by amolsangar** [comment]
![Arch_diagram_v2](https://user-images.githubusercontent.com/41895348/152592306-ad436438-84f9-4ba6-a1f5-3e984c788059.jpg)

### Arch Diagram v2
### Logging service implementation details are yet to be decided and will be implemented if time permits.

**Comment by BhushanPatil38** [comment]
![puzzles_architecture](https://user-images.githubusercontent.com/57348155/152895174-fe3a5b99-056f-46c9-83af-25e361d31747.jpg)

Architecture Diagram Final Version
