### ISSUE TITLE
Microservice for User search history

### ISSUE THREAD

**Issue by vaibhav201297** [airavata-courses/Puzzles#6]
Create a micro-service that allows user to view his recent search history and retrieve result if a same search is done by the user

**Comment by vaibhav201297** [comment]
Finished Java Spring Boot Service with the required end-points

**Comment by amolsangar** [comment]
![API Discussion](https://user-images.githubusercontent.com/41895348/152592690-df71ff60-0e2c-4297-b0f5-20cce697e113.jpg)


### Putting discussion points here
